apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: Atales1234
  GMAIL_USER: atalmendoza03@gmail.com
  GMAIL_APP_PASSWORD: mkjd lpqp iwlh nmrt
