namespace: dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - backend-secrets.yaml

patchesStrategicMerge:
  - configmap-backend.yaml
  - patch-backend-deployment.yaml
  - patch-frontend-deployment.yaml