env:
  - name: PORT
    valueFrom:
      configMapKeyRef:
        name: backend-config
        key: PORT
  - name: DB_HOST
    value: mysql-service
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: backend-secret
        key: DB_USER
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: backend-secret
        key: DB_PASSWORD
  - name: GMAIL_USER
    valueFrom:
      secretKeyRef:
        name: backend-secret
        key: GMAIL_USER
  - name: GMAIL_APP_PASSWORD
    valueFrom:
      secretKeyRef:
        name: backend-secret
        key: GMAIL_APP_PASSWORD
  - name: NODE_ENV
    valueFrom:
      configMapKeyRef:
        name: backend-config
        key: NODE_ENV

