apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RocioMagnoni/atales-k8s-cloud
    targetRevision: dev
    path: overlays/dev/auth-service
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true